//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Grid
{
	public virtual void CreateAndDrawGrid(int row,int column)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Reset()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetCellSelected()
	{
		throw new System.NotImplementedException();
	}

}

