//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

public abstract class RoadObject
{

    public RoadObject[] StartArray;

    public roadPiece[] ReferencePath;
    public roadPiece[] endPoints;
    public roadPiece[] pedestrianStartPoint = null;

    public int cellIndexInGrid;

    public Point coordinate;

    public Image Image;

    public Oriention Oriention;

	public TrafficController TrafficController;

	public void SetOrientation(Oriention arg)
	{
		throw new System.NotImplementedException();
	}

	public void AddConnection(RoadObject next)
	{
		throw new System.NotImplementedException();
	}

	public void Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual RoadObject GetRoadObject()
	{
		throw new System.NotImplementedException();
	}

}

