//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class roadPiece
{
	public virtual TrafficLight trafficlightRefrence
	{
		get;
		set;
	}

	public virtual Random Randomizer
	{
		get;
		set;
	}

	public virtual roadPiece NextArray
	{
		get;
		set;
	}

	public virtual System.Drawing.Point coordinate
	{
		get;
		set;
	}

	public virtual RoadObject RoadObject
	{
		get;
		set;
	}

	public virtual Sensor Sensor
	{
		get;
		set;
	}

	public virtual roadPiece getNext()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Randomize()
	{
		throw new System.NotImplementedException();
	}

	public virtual System.Drawing.Point GetCoordinates()
	{
		throw new System.NotImplementedException();
	}

	public virtual void PushSensorButton()
	{
		throw new System.NotImplementedException();
	}

}

