//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrafficController
{
	public virtual TrafficLight TrafficGroupList
	{
		get;
		set;
	}
    /// <summary>
    /// WHAT THE HELL
    /// </summary>
	public virtual IEnumerable<Sensor> Sensor
	{
		get;
		set;
	}

	public virtual void Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual TrafficLight GetTrafficLight()
	{
		throw new System.NotImplementedException();
	}

}

