//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

public abstract class RoadObject
{

    public virtual RoadObject[] StartArray;

    public roadPiece[] ReferencePath;
    public roadPiece[] endPoints;
    public roadPiece[] pedestrianStartPoint = null;

    public virtual int cellIndexInGrid;

    public virtual Point coordinate;

    public virtual Image Image;

    public virtual Oriention Oriention;

	public virtual TrafficController TrafficController;

	public virtual void SetOrientation(Oriention arg)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddConnection(RoadObject next)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update()
	{
		throw new System.NotImplementedException();
	}

	public virtual RoadObject GetRoadObject()
	{
		throw new System.NotImplementedException();
	}

}

