//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

[Serializable]
public class Sensor
{
    
	public bool State
	{
		get;
		set;
	}

	public void SetState(bool state)
	{
		throw new System.NotImplementedException();
	}

}

