//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrafficController
{
	private  List<TrafficLight> TrafficGroupList{ get; set;}

	public void SetSensor()
	{
        TrafficGroupList = new List<TrafficLight>();
	}

	public  void Update()
	{
		
	}

	public  List<TrafficLight> GetTrafficLight()
	{
        return this.TrafficGroupList;
	}

}

