//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

[Serializable]
public class TrafficLight
{
    // Fields 
    //****************************************************************************************************************************************
    private TrafficColor CurrentColor;
    private Point trafficlightCordinate;
    // Properties
    //*****************************************************************************************************************************************
    public Point TrafficlightCordinate
    {
        get { return trafficlightCordinate; }
        set { trafficlightCordinate = value; }
    }
    // Constructor
    public TrafficLight()
    {
        TrafficlightCordinate = new Point(0, 0);
    }

    //*****************************************************************************************************************************************
    // Methods
    public void SetColor(int color)
    {
        switch (color)
        {
            case 0:
                CurrentColor = TrafficColor.Red;
                break;
            case 1:
                CurrentColor = TrafficColor.Yellow;
                break;
            case 2:
                CurrentColor = TrafficColor.Green;
                break;

        }
    }
    public TrafficColor GetColor()
    {
        return CurrentColor;
    }
    public void SetCorrdinates(Point xyz)
    {
        TrafficlightCordinate = xyz;
    }
    //*****************************************************************************************************************************************
}

