//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TrafficLight
{
	public virtual System.Drawing.Point coordinate
	{
		get;
		set;
	}

	public virtual System.Windows.Forms.PictureBox PictureboxImage
	{
		get;
		set;
	}

	public virtual int counter
	{
		get;
		set;
	}

	public virtual TrafficController TrafficGroup
	{
		get;
		set;
	}

	public virtual TrafficColor GetColor()
	{
		throw new System.NotImplementedException();
	}

	public virtual void setCounter(int Seconds)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetColor(TrafficColor color)
	{
		throw new System.NotImplementedException();
	}

}

