//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;
[Serializable]
public class TrafficController
{
    //******************************************************************************************************************************
    // Feilds & properties
    private List<TrafficLight> TrafficGroupList { get; set; }
    private List<TrafficLight> TrafficGroupListWithPedstrian { get; set; }

    private int innerCounter;                                       // Counter For How many Seconds each traffic - "Stand Alone" - can be set for
    private int outterCounter;                                      //Counter For the pair of each Traffic light;
    //******************************************************************************************************************************
    // constructor

    public TrafficController()
    {
        innerCounter = 6; // Every 6 seconds the timer will change the value By setting
        outterCounter = 0;
        int ColorPicker;
        TrafficGroupList = new List<TrafficLight>();   //  Array with 6 corrdinates 
        TrafficGroupListWithPedstrian = new List<TrafficLight>();// Array with 4 corrdinates
    }

    //******************************************************************************************************************************
    //Methods
    public void SetSensor()
    {
        // TODO
    }

    public void Update()
    {
        // Called at each timer tick 
        // Update Values By changeing the colors of each Cordinate in the traffic light 
        // The update Happens by the inner Counter and Outter Counter 
        innerCounter--;
        foreach (TrafficLight item in TrafficGroupList)
        {
            // TO DO : Form static set color to dynamic set color
            if (innerCounter < 0)
            {
                item.SetColor((int)TrafficColor.Red);
            }
          
        }
        foreach (TrafficLight item in TrafficGroupListWithPedstrian)
        {
            
        }

    }

    public void SetInnerCounter(int Seconds)
    {
        innerCounter = Seconds;
    }
    public void SetOutterCounter(int Seconds)
    {
        outterCounter = Seconds;
    }

    public List<TrafficLight> GetTrafficLight(int index)
    {
        List<TrafficLight> temp = null;
        switch (index)
        {
            case 1 :
                temp = this.TrafficGroupList;
                break;
            case 2 :
                temp = this.TrafficGroupListWithPedstrian;
                break;
        }
        return temp;
    }
    public void AddTrafficLightToRoadPiece(CrossingType ct, TrafficLight obj)
    {
        switch (ct)
        {
            case CrossingType.CrossingWithPedestrian:
                TrafficGroupListWithPedstrian.Add(obj);
                break;

            case CrossingType.CrossingWithoutPedestrian:
                TrafficGroupList.Add(obj);
                break;
        }


    }

    public void ResetTraffic()
    {
        innerCounter = 6;
    }
    public int IncrementListener()
    {
        int holder = outterCounter++;
        holder = holder + 1 % 3;
        return holder;
    }

}

